#!/usr/bin/python3
import sys
def factorize_number(n):
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            return i, n // i
    return None

def factorize_file(file_path):

    with open(file_path, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factors = factorize_number(n)
        if factors:
            print(f"{n}={factors[1]}*{factors[0]}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    try:
        factorize_file(file_path)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
